language: php

sudo: false

php:
  - 7.2
  - 7.3
  - nightly

before_script:
  - curl --version
  - composer install --no-interaction --prefer-source

script: make test

matrix:
  fast_finish: true